### ISSUE TITLE
Полная очистка дерева без его удаления

### ISSUE THREAD

**Issue by avasyukov** [89637706045/II-semestr#1]
Тест-кейс:
```c++
int main()
{
    Container* c = new SimpleList();
    c->insert(1);
    c->remove(1);
    c->insert(2);
    c->print();
    delete c;
    return 0;
}
```

Ожидаем на выходе дерево с единственным элементом 2. Получаем по факту дерево с двумя элементами.

**Comment by 89637706045** [comment]
Так кам же выскакивает сообщение:

This tree has only one element, so we cann`t delete it!

что мы не будем удалять этот элемент ибо единственный и корневой, в таком случае это тоже самое, что удалить дерево

то есть, это действие не имеет смысла

**Comment by 89637706045** [comment]
хотя может и имеет

**Comment by 89637706045** [comment]
короче, сложный вопрос имеет смысл это или нет, поэтому просто залью другу версию, где так сделать можно:

**Comment by 89637706045** [comment]
https://github.com/89637706045/II-semestr/blob/master/BinaryTree_final_another_ver.cpp

**Comment by avasyukov** [comment]
Да, новая реализация проблемы не имеет. Тикет закрываю.
